title: Anmol Chaure
email: chaurea@fzp.czu.cz
description: >-
  Research Technician for Environmental Health Research Group, CULS, Prague
github_username: anmolchaure
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Anmol Chaure"
  avatar: "assets/images/IMG_1807-modified.png"
  bio: "Environmental Researcher · MSc student at CULS Prague"
  location: "Prague, Czech Republic"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:chaurea@fzp.czu.cz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anmolchaure"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0001-1707-8694"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://researchgate.net/profile/yourprofile"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anmolchaure"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
